### ISSUE TITLE
[FEATURE] {ICR}-{PDF解析套件測試}

### ISSUE THREAD

**Issue by brucehuang616** [TPI-AIPD/Cathay-Private-Equity_ICR#2]
根據客戶提供的PDF，測試是否能通過PDF解析套件直接抓取用戶所需表格跟欄位
https://drive.google.com/drive/folders/1g5QMBo1Artt3JNkfionPGEFQLmyaLoVZ

目前發現有部分PDF表格是圖片形式，再麻煩協助統計圖片形式跟結構化資料形式的數量

**Comment by HowardChou24** [comment]
### 2024/12/23

#### 情境說明

* 於專案「國泰私募」提供之10檔PDF基金文件中，分析提取PDF檔案中的「資料表」以及對應資料欄位中的「數值」與「參數」。
* 將初步使用Python套件嘗試分析PDF結構提取目標文字與資料表。
* 資料提取精確度需達到 95% 以上。

#### 測試與驗證

* 經觀測與驗證十檔基金均為「結構化」pdf，可使用頗析結構的方案進行頗析。
* 如下為實驗Python pdf頗析相關套件結果：
![image](https://github.com/user-attachments/assets/c6de44aa-8333-49ea-9ddd-ab59d4874d67)
排除收費的套件：LLMWhisperer、Pdftables
選定使用Python套件：「Pdfplumber」

#### 呈現結果

來源基金pdf中的目標資料表：
![image](https://github.com/user-attachments/assets/9cc00833-d575-480f-a05f-569013a416df)

試提取資料表中的資料成csv檔：
![image](https://github.com/user-attachments/assets/ae15dbbe-9672-453e-8d7a-d5d5c7981977)

由觀測得知此成果達成本專案標示精確度目標，故選用此套件實作。
